site_name: Music Assistant
site_url: https://music-assistant.github.io/

#repo_name: music-assistant
#repo_url: https://github.com/music-assistant

nav:
  - Home: index.md
  - Installation: installation.md
  - Home Assistant Integration:
    - integration/index.md
    - Installation: integration/installation.md
    - Migrating from HACS: integration/migrate.md
    - Announcements: integration/announcements.md
    - Play Media Action: faq/massplaymedia.md
    - Play Announcement Action: faq/massannounce.md
    - Search Action: faq/masssearch.md
    - Get Library Action: faq/get_library.md
    - Get Queue Action: faq/get_queue.md
    - Transfer Queue Action: faq/masstransfer.md
  - Companion App: companion-app.md
  - Usage: 
    - General: usage.md
    - UI: ui.md
    - Groups: faq/groups.md
    - DSP Parametric EQ: dsp/parametriceq.md
    - DSP Tone Controls: dsp/tonecontrols.md
    - How Do I...: faq/how-to.md
    - I Want To Stream To: faq/stream-to.md
    - Technical Info: faq/tech-info.md
    - Troubleshooting: faq/troubleshooting.md
  - Music Providers:
    - music-providers/index.md
    - Apple Music: music-providers/apple-music.md
    - Builtin: music-providers/builtin.md
    - Deezer: music-providers/deezer.md
    - iBroadcast: music-providers/ibroadcast.md
    - Jellyfin: music-providers/jellyfin.md
    - Local Files: music-providers/filesystem.md
    - Plex: music-providers/plex.md
    - Qobuz: music-providers/qobuz.md
    - Radio Browser: music-providers/radio-browser.md
    - SiriusXM: music-providers/siriusxm.md
    - SoundCloud: music-providers/soundcloud.md
    - Spotify: music-providers/spotify.md
    - Subsonic: music-providers/subsonic.md
    - Tidal: music-providers/tidal.md
    - TuneIn: music-providers/tunein.md
    - YouTube Music: music-providers/youtube-music.md
  - Player Providers:
    - player-support/index.md
    - AirPlay: player-support/airplay.md
    - Bluesound: player-support/bluesound.md
    - DLNA: player-support/dlna.md
    - Fully Kiosk: player-support/fully-kiosk.md
    - Google Cast: player-support/google-cast.md
    - Home Assistant: player-support/ha.md
    - Slimproto: player-support/slimproto.md
    - Snapcast: player-support/snapcast.md
    - Sonos: player-support/sonos.md
  - Support: support.md
  - I Want to Help / Donate: 
    - help/index.md
    - Translations: help/lokalise.md
  - Release Cycle: release.md

theme:
  custom_dir: overrides
  favicon: assets/favicon-orange.png
  logo: assets/transparent-logo.png
  name: material
  font:
    text: Roboto
    code: JetBrains Mono
    
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    
    - toc.integrate
    
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    scheme: music-assistant
extra_css:
  - stylesheets/extra.css  

plugins:
  - social:
      cards_layout_options:
        font_family: JetBrains Mono
  - search:
  - minify:
      minify_html: true 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/music-assistant
      name: Music Asisstant on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/kaVm8hGpne
      name: Music Assistant on Discord
    - icon: lokalise-logo-colour
      link: https://lokalise.com/
      name: Translations by Lokalise  
    #- icon: fontawesome/brands/dev
    #  link: ./developer-docs/dev-docs/
    #  name: Developer Docs

      
markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/music-assistant"  target="_blank" rel="noopener">Music Assistant</a>
