site_name: Music Assistant
site_url: https://music-assistant.github.io/

repo_name: music-assistant
repo_url: https://github.com/music-assistant

nav:
  - Music Assistant: index.md
  - Server Installation: Installation.md
  - Home Assistant Integration: integration.md
  - Companion App: companion-app.md
  - Music Providers:
    - Deezer: music-providers/deezer.md
    - Local Files: music-providers/filesystem.md
    - Plex: music-providers/plex.md
    - Qobuz: music-providers/qobuz.md
    - Radio Browser: music-providers/radio-browser.md
    - SoundCloud: music-providers/soundcloud.md
    - Spotify: music-providers/spotify.md
    - Tidal: music-providers/tidal.md
    - TuneIn: music-providers/tunein.md
    - YouTube Music: music-providers/youtube-music.md
  - Player Support:
    - AirPlay: player-support/airplay.md
    - DLNA: player-support/dlna.md
    - Google Cast: player-support/google-cast.md
    - Slimproto: player-support/slimproto.md
    - Snapcast: player-support/snapcast.md
    - Sonos: player-support/sonos.md
    - Universal Groups: player-support/universal.md
    
  - FAQ:
    - Music Providers: faq/providers.md
    - How To: faq/how-to.md 
  - Developer Docs: developer-docs/dev-docs.md  

theme:
  favicon: assets/favicon.png
  logo: assets/icon.png
  name: material
  font:
    text: Roboto
    code: JetBrains Mono
    
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

    - toc.integrate
    
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: deep-orange 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: white
      accent: lime

plugins:
  - social:
      cards_layout_options:
        font_family: JetBrains Mono
  - search:
  - minify:
      minify_html: true 
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/music-assistant
    - icon: fontawesome/brands/discord
      link: https://discord.gg/kaVm8hGpne
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/music-assistant/ 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/music-assistant"  target="_blank" rel="noopener">Music Assistant</a>
